version: '3.9'

services:
  db:
    image: mysql/mysql-server:8.0.29
    volumes:
      - ./db:/var/lib/mysql
    command: [ 'mysqld', '--authentication_policy=mysql_native_password' ]
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=task_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    networks:
      - app
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  app:
    image: task-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/task_db
    networks:
      - app

networks:
  app:
    name: app